import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class GradeRequestDto {
  @ApiProperty({
    description: 'The original task that was assigned',
    example: 'Write a python function to add two numbers',
  })
  @IsString()
  @IsNotEmpty()
  task: string;

  @ApiProperty({
    description: 'The output generated by the LLM that needs to be graded',
    example: 'def add(a, b):\n  return a + b',
  })
  @IsString()
  @IsNotEmpty()
  output: string;
}
